name: Check sources
on:
  push:
    branches-ignore:
      - main
jobs:
  testscript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check script
        run: test -e run.sh
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@master
  tests:
    runs-on: ubuntu-latest
    needs: shellcheck
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make tests
  doc:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make doc
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action/container/action
      with:
         tocken:${{ secrets.GITHUB_TOKEN }}
